version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000

  shop2:
    build:
      context: .
      dockerfile: ./app2/Dockerfile
    volumes:
      - ./app2:/app2
    ports:
      - 8001:8001
